theme = "catppuccin_macchiato_modified"

[editor]
color-modes = true
bufferline = "multiple"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
# normal = "bar"
# select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = false

[keys.select]
p = "replace_with_yanked" # No life without this   
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

[keys.normal]
p = "replace_with_yanked" # No life without this   
"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
